% 1. Priprav zoznam súborov (napríklad jeden axiálny a jeden sagitálny rez)
subory = {"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm118.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm123.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm003.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm008.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm013.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm018.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm023.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm028.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm033.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm038.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm043.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm048.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm053.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm058.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm063.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm068.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm073.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm078.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm083.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm088.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm093.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm098.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm103.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm108.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_axial_2\MRIm113.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm118.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm123.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm003.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm008.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm013.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm018.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm023.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm028.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm033.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm038.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm043.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm048.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm053.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm058.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm063.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm068.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm073.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm078.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm083.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm088.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm093.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm098.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm103.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm108.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm113.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm118.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_coronal_2\MRIm123.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm003.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm008.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm013.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm018.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm023.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm028.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm033.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm038.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm043.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm048.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm053.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm058.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm063.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm068.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm073.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm078.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm083.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm088.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm093.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm098.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm103.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm108.dcm", ...
"C:\Users\akara\Desktop\Martin_APVV\Data_Dano_poslat\P4_pHMK\relaxometria\P4_T2_sagittal_2\MRIm113.dcm"};

% Spustenie tvojej funkcie pre získanie 3D Volume dát
[V, X, Y, Z] = PlanesToVolume(subory,voxel);

V = rescale(V, 0, 1);

% --- OPRAVA 1: Priehľadnosť čierneho pozadia (Prahovanie na NaN) ---
% Pozadie a šum okolo anatómie zmeníme na NaN, čím sa stane neviditeľným.
prah_pozadia = 0.6; 
V(V < prah_pozadia) = NaN; 

% 2. Vytvorenie grafického okna
figure;
hold on;

% Vykreslenie rezov
hx = slice(X, Y, Z, V, unique(X), unique(Y), unique(Z));

% Úprava základných vlastností
set(hx, 'EdgeColor', 'none'); % Vypnutie otravnej mriežky okolo pixelov
colormap('gray');             % Štandardná MRI sivá škála
daspect([1 1 1]);             % Zachovanie reálnych proporcií (1mm na osi X = 1mm na osi Y)
view(3);                      % 3D pohľad
grid on;

% --- OPRAVA 2: Odstránenie lesku a tieňov (Matný vzhľad MRI) ---
% Nastavíme vlastnosti povrchu tak, aby sa správal ako plochý matný obrázok
set(hx, 'AmbientStrength', 1.0);  % Maximálne okolité svetlo (stály jas z každého uhla)
set(hx, 'DiffuseStrength', 0.0);  % Žiadne rozptyľovanie bodového svetla
set(hx, 'SpecularStrength', 0.0); % NULOVÝ LESK (úplne odstráni zrkadlové odlesky)


% % 1. Výpočet objemu a priestorových mriežok
% [V, X_grid, Y_grid, Z_grid] = DICOMPlanesToVolume(subory, voxel, true);
% 
% V(isnan(V)) = 0;
% 
% V = rescale(V, 0, 1);
% 
% % 2. Vytvorenie okna a vykreslenie (napríklad pevný povrch pľúc / tkaniva)
% figure;
% isovalue = 0.2; % Prispôsob podľa intenzity v DICOMe
% fv = isosurface(X_grid, Y_grid, Z_grid, V, isovalue);
% p = patch(fv);
% 
% % Úprava vzhľadu
% p.FaceColor = [0.8 0.4 0.4];
% p.EdgeColor = 'none';
% 
% % --- AKTIVÁCIA A FORMÁTOVANIE FYZICKÝCH OSÍ ---
% axis tight;     % Oreže prázdny priestor na minimum
% axis equal;     % ZABEZPEČÍ, že 1 mm na osi X bude na obrazovke rovnako dlhý ako 1 mm na osi Z
% box on;         % Uzavrie graf do 3D klietky
% grid on;        % Zapne čiary mriežky pre lepšiu orientáciu v milimetroch
% 
% % Popisy osí (DICOM orientácia pacienta)
% xlabel('Os X (RL - Right/Left)');
% ylabel('Os Y (AP - Anterior/Posterior)');
% zlabel('Os Z (FH - Feet/Head)');
% 
% view(3);
% camlight; lighting gouraud;